apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: app-auth-proxy
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
        - PATCH
  service:
    host: auth-proxy
    name: app-auth-proxy
    port: 80
